"use client";

import Link from "next/link";
import { FocusTimer } from "@/components/focus/focus-timer";
import { Icon } from "@/components/ui/icon";
import { LoadingState } from "@/components/ui/loading-state";
import { formatMinutes, getLastDateKeys, getLearningStreak, isDateThisWeek, toDateKey } from "@/lib/date-utils";
import { useSuOsStore } from "@/lib/store/su-os-store";

export function DashboardV2() {
  const { data, hydrated, toggleTask } = useSuOsStore();
  if (!hydrated) return <LoadingState/>;
  const today = toDateKey();
  const todayTasks = data.tasks.filter((task) => task.dueDate === today).sort((a, b) => Number(b.isMIT) - Number(a.isMIT) || a.order - b.order);
  const completed = todayTasks.filter((task) => task.completed).length;
  const progress = todayTasks.length ? Math.round(completed / todayTasks.length * 100) : 0;
  const mits = todayTasks.filter((task) => task.isMIT);
  const todayFocus = data.focusSessions.filter((session) => toDateKey(new Date(session.completedAt)) === today).reduce((sum, session) => sum + session.durationMinutes, 0);
  const todayLearning = data.learningSessions.filter((session) => session.date === today).reduce((sum, session) => sum + session.durationMinutes, 0);
  const weekLearning = data.learningSessions.filter((session) => isDateThisWeek(session.date)).reduce((sum, session) => sum + session.durationMinutes, 0);
  const learningStreak = getLearningStreak(data.learningSessions.map((session) => session.date));
  const trend = getLastDateKeys(7).map((date) => ({ date, minutes: data.learningSessions.filter((session) => session.date === date).reduce((sum, session) => sum + session.durationMinutes, 0) + data.focusSessions.filter((session) => toDateKey(new Date(session.completedAt)) === date).reduce((sum, session) => sum + session.durationMinutes, 0) }));
  const maxTrend = Math.max(...trend.map((item) => item.minutes), 1);
  const activeProjects = data.projects.filter((project) => project.status === "active");
  const recentNote = [...data.notes].filter((note) => !note.archived).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0];

  return (
    <div>
      <section className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">{new Intl.DateTimeFormat("zh-CN", { weekday: "long", month: "long", day: "numeric" }).format(new Date())}</p><h1 className="text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">你好，Su.</h1><p className="mt-2 text-sm text-[#8c8c98]">新的一天，从最重要的一件事开始。</p></div><Link href="/tasks" className="primary-button flex w-fit items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-semibold text-white"><Icon name="plus" size={16}/>快速记录任务</Link></section>
      <section className="grid grid-cols-1 gap-4 lg:grid-cols-12">
        <article className="card relative overflow-hidden p-5 sm:p-6 lg:col-span-7"><div className="pointer-events-none absolute -right-16 -top-20 size-52 rounded-full bg-[#9b87f5]/10 blur-3xl"/><div className="relative mb-5 flex items-start justify-between"><div><p className="eyebrow">Today</p><h2 className="mt-2 text-lg font-semibold">今日任务</h2></div><Link href="/today" className="flex items-center gap-1 text-xs text-[#9b87f5]">查看全部 <Icon name="arrow" size={13}/></Link></div><div className="glass-control relative mb-4 flex items-center gap-4 rounded-2xl p-4"><div className="relative grid size-16 shrink-0 place-items-center rounded-full shadow-[0_0_28px_rgba(155,135,245,0.14)]" style={{ background: `conic-gradient(#aa98ff ${progress}%, rgba(255,255,255,.07) 0)` }}><div className="absolute size-[52px] rounded-full bg-[#111522]/90 backdrop-blur-xl"/><span className="relative text-xs font-bold">{progress}%</span></div><div><p className="text-sm font-medium">今天已完成 {completed} / {todayTasks.length}</p><p className="mt-1 text-xs leading-5 text-[#777783]">MIT {mits.length} 项 · 专注 {formatMinutes(todayFocus)}</p></div></div>{mits.length > 0 && <div className="mb-3 flex flex-wrap gap-2">{mits.map((task) => <span key={task.id} className="rounded-full bg-[#9b87f5]/12 px-2.5 py-1 text-[9px] text-[#b7acfa]">MIT · {task.title}</span>)}</div>}<div className="space-y-1.5">{todayTasks.length ? todayTasks.slice(0, 4).map((task) => <button key={task.id} onClick={() => toggleTask(task.id)} className="group flex w-full items-center gap-3 rounded-xl p-2.5 text-left transition hover:bg-white/[0.025]"><span className={`grid size-5 shrink-0 place-items-center rounded-md border transition ${task.completed ? "border-[#9b87f5] bg-[#9b87f5] text-white" : "border-white/15 text-transparent group-hover:border-[#9b87f5]/70"}`}><Icon name="check" size={12} strokeWidth={2.4}/></span><span className="min-w-0 flex-1"><span className={`block truncate text-[13px] ${task.completed ? "text-[#666671] line-through" : "text-[#d2d2d8]"}`}>{task.title}</span><span className="mt-0.5 block text-[10px] text-[#676773]">{task.time ?? "全天"} · {data.projects.find((project) => project.id === task.projectId)?.name ?? "无项目"}</span></span><span className={`size-1.5 rounded-full ${task.priority === "high" ? "bg-[#fb7185]" : task.priority === "medium" ? "bg-[#fbbf77]" : "bg-[#6ee7b7]"}`}/></button>) : <p className="py-8 text-center text-xs text-[#6f7584]">今天还没有任务</p>}</div></article>
        <FocusTimer/>
        <article className="card p-5 sm:p-6 lg:col-span-7"><div className="mb-6 flex items-start justify-between"><div><p className="eyebrow">This Week</p><h2 className="mt-2 text-lg font-semibold">学习与专注</h2><p className="mt-1 text-[10px] text-[#6f7584]">今日学习 {formatMinutes(todayLearning)}</p></div><div className="text-right"><p className="text-xl font-semibold">{formatMinutes(weekLearning)}</p><p className="mt-1 text-[10px] text-[#6ee7b7]">本周学习</p></div></div><div className="flex h-40 items-end justify-between gap-2 border-b border-white/[0.06] pb-1 sm:gap-4">{trend.map((item) => <div key={item.date} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="relative flex h-full w-full items-end justify-center"><div className={`w-full max-w-8 rounded-t-lg transition hover:brightness-125 ${item.date === today ? "bg-gradient-to-t from-[#7562db] to-[#b5a8ff]" : "bg-white/[0.08]"}`} style={{ height: `${Math.max(item.minutes ? 8 : 2, item.minutes / maxTrend * 100)}%` }}/></div><span className={`text-[10px] ${item.date === today ? "text-[#b5a8ff]" : "text-[#64646f]"}`}>{new Intl.DateTimeFormat("zh-CN", { weekday: "short" }).format(new Date(`${item.date}T12:00:00`))}</span></div>)}</div></article>
        <article className="card p-5 sm:p-6 lg:col-span-5"><div className="mb-5 flex items-start justify-between"><div><p className="eyebrow">Projects</p><h2 className="mt-2 text-lg font-semibold">项目进度</h2></div><Link href="/projects" className="grid size-8 place-items-center rounded-lg text-[#777783] hover:bg-white/[0.04]"><Icon name="arrow" size={16}/></Link></div>{activeProjects.length ? <div className="space-y-5">{activeProjects.slice(0, 4).map((project) => { const tasks = data.tasks.filter((task) => task.projectId === project.id); const done = tasks.filter((task) => task.completed).length; const value = tasks.length ? Math.round(done / tasks.length * 100) : 0; return <div key={project.id}><div className="mb-2 flex items-end justify-between"><div><p className="text-[13px] text-[#d0d0d6]">{project.name}</p><p className="mt-1 text-[10px] text-[#656570]">{done}/{tasks.length} 个任务</p></div><span className="text-xs font-semibold text-[#9b87f5]">{value}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.055]"><div className="h-full rounded-full bg-gradient-to-r from-[#8c78ff] to-[#6ee7b7]" style={{ width: `${value}%` }}/></div></div>; })}</div> : <p className="py-10 text-center text-xs text-[#6f7584]">还没有进行中的项目</p>}</article>
        <Link href="/notes" className="card card-hover group p-5 sm:p-6 lg:col-span-4"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#fbbf77]/10 text-[#fbbf77]"><Icon name="note" size={19}/></span><Icon name="arrow" size={16} className="text-[#5e5e69] transition group-hover:translate-x-1 group-hover:text-white"/></div><p className="mt-7 text-xs text-[#777783]">最近笔记</p><h3 className="mt-2 line-clamp-2 text-sm font-medium leading-6">{recentNote?.title ?? "还没有笔记"}</h3><p className="mt-3 text-[10px] text-[#5f5f6a]">{recentNote ? recentNote.tags.map((tag) => `#${tag}`).join(" ") || "无标签" : "创建第一篇笔记"}</p></Link>
        <Link href="/learning" className="card card-hover group p-5 sm:p-6 lg:col-span-4"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#6ee7b7]/10 text-[#6ee7b7]"><Icon name="book" size={19}/></span><Icon name="arrow" size={16} className="text-[#5e5e69] transition group-hover:translate-x-1 group-hover:text-white"/></div><p className="mt-7 text-xs text-[#777783]">连续学习</p><h3 className="mt-2 text-2xl font-semibold">{learningStreak} <span className="text-xs font-normal text-[#777783]">天</span></h3><p className="mt-3 text-[10px] text-[#5f5f6a]">今日累计 {formatMinutes(todayLearning)}</p></Link>
        <Link href="/ai" className="card card-hover group relative overflow-hidden p-5 sm:p-6 lg:col-span-4"><div className="absolute -bottom-12 -right-10 size-32 rounded-full bg-[#9b87f5]/15 blur-2xl"/><div className="relative flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-[#9b87f5]/12 text-[#aa98fa]"><Icon name="sparkles" size={19}/></span><Icon name="arrow" size={16} className="text-[#5e5e69] transition group-hover:translate-x-1 group-hover:text-white"/></div><p className="relative mt-7 text-xs text-[#777783]">Su Assistant</p><h3 className="relative mt-2 text-sm font-medium">需要帮你整理今天吗？</h3><p className="relative mt-3 text-[10px] text-[#5f5f6a]">本地演示回复 · 未连接 API</p></Link>
      </section>
    </div>
  );
}
